// ubx_data_fields.h
//
// Enumeration of every database field that the UBX message update handlers may
// write.  Field enum values are kept 1-to-1 compatible with the old CDatabase::DATA_t
// so that consumer code using numeric indices continues to compile unmodified.
//
// Design notes
// ─────────────
// • All field IDs are plain integers; there is NO CVar / CDatabase dependency.
// • Array fields (SAT info, MON-RF blocks, …) use contiguous ID ranges exactly
//   as in the old enum (base_id + offset).
// • DATA_PARSE acts as the "ceiling" sentinel – only ids < DATA_PARSE may be
//   written to the store.
// • DATA_NUM is the total count of allocated storage slots.
//
// Thread-safety:  plain enum; no synchronisation needed.

#pragma once

#include <cstdint>

namespace ubx
{
namespace database
{

enum
{
    MAX_MON_RF_BLOCK        = 4,
    MAX_SATELLITES_IN_VIEW  = 64,
    MAX_ALL_GNSS_SIGNALS    = (MAX_SATELLITES_IN_VIEW * 2),
    MAX_ESF_SENSORS         = 32,   ///< Max sensor blocks reported by ESF-STATUS
    MAX_ESF_MEAS_DATA       = 32,   ///< Max measurement data words per ESF-MEAS
    MAX_RXM_MEASX_MEAS      = 64,   ///< Max satellite measurement blocks per RXM-MEASX
    MAX_MON_IO_PORTS        = 8,    ///< Max I/O port blocks per MON-IO
    MAX_MON_SPAN_RF_BLOCKS  = 4,    ///< Max RF blocks reported by MON-SPAN
};

enum data_field : uint16_t
{
    // ── UBX-NAV-PVT ──────────────────────────────────────────────────────────
    DATA_UBX_NAV_PVT_ITOW = 0,
    DATA_UBX_NAV_PVT_FIXTYPE,
    DATA_UBX_NAV_PVT_LAT,
    DATA_UBX_NAV_PVT_LON,
    DATA_UBX_NAV_PVT_ALT,
    DATA_UBX_NAV_PVT_HMSL,
    DATA_UBX_NAV_PVT_FLAGS,
    DATA_UBX_NAV_PVT_FLAGS2,
    DATA_UBX_NAV_PVT_NUMSV,
    DATA_UBX_NAV_PVT_GSPEED,
    DATA_UBX_NAV_PVT_VEHICLE_HEADING_DEGREE,
    DATA_UBX_NAV_PVT_MOTION_HEADING_DEGREE,
    DATA_UBX_NAV_PVT_MAGNETIC_DECLINATION,
    DATA_UBX_NAV_PVT_GEAR,
    DATA_UBX_NAV_PVT_TIME_STATUS,
    DATA_UBX_NAV_PVT_VEL_N,
    DATA_UBX_NAV_PVT_VEL_E,
    DATA_UBX_NAV_PVT_VEL_D,
    DATA_UBX_NAV_PVT_T_ACC,
    DATA_UBX_NAV_PVT_H_ACC,
    DATA_UBX_NAV_PVT_V_ACC,
    DATA_UBX_NAV_PVT_S_ACC,
    DATA_UBX_NAV_PVT_HEAD_ACC,
    DATA_UBX_NAV_PVT_YEAR,
    DATA_UBX_NAV_PVT_MONTH,
    DATA_UBX_NAV_PVT_DAY,
    DATA_UBX_NAV_PVT_HOUR,
    DATA_UBX_NAV_PVT_MINUTE,
    DATA_UBX_NAV_PVT_SECOND,
    DATA_UBX_NAV_PVT_MILI_SECOND,
    DATA_UBX_NAV_PVT_MICRO_SECOND,
    DATA_UBX_NAV_PVT_TIMESTAMP,
    DATA_UBX_NAV_PVT_TIME_VALID,

    // ── UBX-NAV-DOP ──────────────────────────────────────────────────────────
    DATA_UBX_NAV_GEOMETRIC_DILUTION_OF_PRECISION,
    DATA_UBX_NAV_POSITION_DILUTION_OF_PRECISION,
    DATA_UBX_NAV_TIME_DILUTION_OF_PRECISION,
    DATA_UBX_NAV_VERTICAL_DILUTION_OF_PRECISION,
    DATA_UBX_NAV_HORIZONAL_DILUTION_OF_PRECISION,

    // ── UBX-NAV-EELL ─────────────────────────────────────────────────────────
    DATA_UBX_SEMI_MAJOR_AXIS_ACC,
    DATA_UBX_SEMI_MINOR_AXIS_ACC,
    DATA_UBX_SEMI_MAJOR_AXIS_ORIENTATION,

    // ── UBX-NAV-TIMEGPS ──────────────────────────────────────────────────────
    DATA_UBX_NAV_GPSTIME_TOW,
    DATA_UBX_NAV_GPSTIME_WEEK,
    DATA_UBX_NAV_GPSTIME_LEAP_SECONDS,

    // ── UBX-NAV-STATUS ───────────────────────────────────────────────────────
    DATA_UBX_TTFF,

    // ── UBX-TIM-TP ───────────────────────────────────────────────────────────
    DATA_TIME_PULSE_TIMESTAMP,
    DATA_TIME_PULSE_QUANTIZATION_ERROR,
    DATA_TIME_PULSE_UTC_TIME_BASE,
    DATA_TIME_PULSE_UTC_AVAILABLE,
    DATA_TIME_PULSE_RAIM_ACTIVE,
    DATA_TIME_PULSE_Q_ERROR_VALID,
    DATA_TIME_PULSE_TP_LOCKED_GNSS,
    DATA_TIME_PULSE_TIME_REF,
    DATA_TIME_PULSE_UTC_STANDARD,

    // ── UBX-MON-RF ───────────────────────────────────────────────────────────
    DATA_UBX_MON_RF_NBLOCKS,
    DATA_UBX_MON_RF_BLOCK_ID,
    DATA_UBX_MON_RF_BLOCK_ID_X         = (MAX_MON_RF_BLOCK + DATA_UBX_MON_RF_BLOCK_ID),
    DATA_UBX_MON_RF_AGCCNT,
    DATA_UBX_MON_RF_AGCCNT_X           = (MAX_MON_RF_BLOCK + DATA_UBX_MON_RF_AGCCNT),
    DATA_UBX_MON_RF_NOISEPERMS,
    DATA_UBX_MON_RF_NOISEPERMS_X       = (MAX_MON_RF_BLOCK + DATA_UBX_MON_RF_NOISEPERMS),
    DATA_UBX_MON_RF_JAMIND,
    DATA_UBX_MON_RF_JAMIND_X           = (MAX_MON_RF_BLOCK + DATA_UBX_MON_RF_JAMIND),

    // ── UBX-NAV-SAT ──────────────────────────────────────────────────────────
    DATA_SATELLITES_IN_VIEW,
    DATA_SATELLITES_IN_VIEW_GNSSID,
    DATA_SATELLITES_IN_VIEW_GNSSID_X    = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_GNSSID,
    DATA_SATELLITES_IN_VIEW_SVID,
    DATA_SATELLITES_IN_VIEW_SVID_X      = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_SVID,
    DATA_SATELLITES_IN_VIEW_AZIMUTH,
    DATA_SATELLITES_IN_VIEW_AZIMUTH_X   = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_AZIMUTH,
    DATA_SATELLITES_IN_VIEW_ELEVATION,
    DATA_SATELLITES_IN_VIEW_ELEVATION_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_ELEVATION,
    DATA_SATELLITES_IN_VIEW_CN0_RATIO,
    DATA_SATELLITES_IN_VIEW_CN0_RATIO_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_CN0_RATIO,
    DATA_SATELLITES_IN_VIEW_ALMANAC,
    DATA_SATELLITES_IN_VIEW_ALMANAC_X   = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_ALMANAC,
    DATA_SATELLITES_IN_VIEW_EPHEMERIS,
    DATA_SATELLITES_IN_VIEW_EPHEMERIS_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_EPHEMERIS,
    DATA_SATELLITES_IN_VIEW_HEALTH,
    DATA_SATELLITES_IN_VIEW_HEALTH_X    = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_HEALTH,
    DATA_SATELLITES_IN_VIEW_USED,
    DATA_SATELLITES_IN_VIEW_USED_X      = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_USED,
    DATA_SATELLITES_IN_VIEW_DIFF_CORR,
    DATA_SATELLITES_IN_VIEW_DIFF_CORR_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_DIFF_CORR,
    DATA_SATELLITES_IN_VIEW_SBAS_USED,
    DATA_SATELLITES_IN_VIEW_SBAS_USED_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_SBAS_USED,
    DATA_SATELLITES_IN_VIEW_RTCM_USED,
    DATA_SATELLITES_IN_VIEW_RTCM_USED_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_RTCM_USED,
    DATA_SATELLITES_IN_VIEW_L1_SIG_ID,
    DATA_SATELLITES_IN_VIEW_L1_SIG_ID_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_L1_SIG_ID,
    DATA_SATELLITES_IN_VIEW_L1_CN0,
    DATA_SATELLITES_IN_VIEW_L1_CN0_X    = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_L1_CN0,
    DATA_SATELLITES_IN_VIEW_L5_SIG_ID,
    DATA_SATELLITES_IN_VIEW_L5_SIG_ID_X = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_L5_SIG_ID,
    DATA_SATELLITES_IN_VIEW_L5_CN0,
    DATA_SATELLITES_IN_VIEW_L5_CN0_X    = MAX_SATELLITES_IN_VIEW + DATA_SATELLITES_IN_VIEW_L5_CN0,

    // ── UBX-NAV2-PVT (secondary navigation solution) ─────────────────────────
    DATA_UBX_NAV2_PVT_ITOW,
    DATA_UBX_NAV2_PVT_FIXTYPE,
    DATA_UBX_NAV2_PVT_LAT,
    DATA_UBX_NAV2_PVT_LON,
    DATA_UBX_NAV2_PVT_ALT,
    DATA_UBX_NAV2_PVT_HMSL,
    DATA_UBX_NAV2_PVT_FLAGS,
    DATA_UBX_NAV2_PVT_FLAGS2,
    DATA_UBX_NAV2_PVT_NUMSV,
    DATA_UBX_NAV2_PVT_GSPEED,
    DATA_UBX_NAV2_PVT_VEHICLE_HEADING_DEGREE,
    DATA_UBX_NAV2_PVT_MOTION_HEADING_DEGREE,
    DATA_UBX_NAV2_PVT_MAGNETIC_DECLINATION,
    DATA_UBX_NAV2_PVT_VEL_N,
    DATA_UBX_NAV2_PVT_VEL_E,
    DATA_UBX_NAV2_PVT_VEL_D,
    DATA_UBX_NAV2_PVT_H_ACC,
    DATA_UBX_NAV2_PVT_V_ACC,
    DATA_UBX_NAV2_PVT_YEAR,
    DATA_UBX_NAV2_PVT_MONTH,
    DATA_UBX_NAV2_PVT_DAY,
    DATA_UBX_NAV2_PVT_HOUR,
    DATA_UBX_NAV2_PVT_MINUTE,
    DATA_UBX_NAV2_PVT_SECOND,
    DATA_UBX_NAV2_PVT_MILI_SECOND,
    DATA_UBX_NAV2_PVT_MICRO_SECOND,
    DATA_UBX_NAV2_PVT_TIME_VALID,
    DATA_UBX_NAV2_PVT_TIMESTAMP,

    // ── UBX-NAV2-DOP ─────────────────────────────────────────────────────────
    DATA_UBX_NAV2_GEOMETRIC_DILUTION_OF_PRECISION,
    DATA_UBX_NAV2_POSITION_DILUTION_OF_PRECISION,
    DATA_UBX_NAV2_TIME_DILUTION_OF_PRECISION,
    DATA_UBX_NAV2_VERTICAL_DILUTION_OF_PRECISION,
    DATA_UBX_NAV2_HORIZONAL_DILUTION_OF_PRECISION,

    // ── UBX-NAV2-EELL ────────────────────────────────────────────────────────
    DATA_UBX_NAV2_SEMI_MAJOR_AXIS_ACC,
    DATA_UBX_NAV2_SEMI_MINOR_AXIS_ACC,
    DATA_UBX_NAV2_SEMI_MAJOR_AXIS_ORIENTATION,

    // ── UBX-NAV2-TIMEGPS ─────────────────────────────────────────────────────
    DATA_UBX_NAV2_GPSTIME_TOW,
    DATA_UBX_NAV2_GPSTIME_WEEK,
    DATA_UBX_NAV2_GPSTIME_LEAP_SECONDS,

    // ── UBX-NAV-ODO ──────────────────────────────────────────────────────────
    DATA_UBX_NAV_ODO_ITOW,
    DATA_UBX_NAV_ODO_DISTANCE,
    DATA_UBX_NAV_ODO_TOTAL_DISTANCE,
    DATA_UBX_NAV_ODO_DISTANCE_STD,

    // ── UBX-ESF-INS ──────────────────────────────────────────────────────────
    DATA_UBX_ESF_INS_ITOW,
    DATA_UBX_ESF_INS_X_ANG_RATE,
    DATA_UBX_ESF_INS_Y_ANG_RATE,
    DATA_UBX_ESF_INS_Z_ANG_RATE,
    DATA_UBX_ESF_INS_X_ACCEL,
    DATA_UBX_ESF_INS_Y_ACCEL,
    DATA_UBX_ESF_INS_Z_ACCEL,
    DATA_UBX_ESF_INS_BITFIELD0,

    // ── UBX-ESF-STATUS ───────────────────────────────────────────────────────
    DATA_UBX_ESF_STATUS_ITOW,
    DATA_UBX_ESF_STATUS_FUSION_MODE,
    DATA_UBX_ESF_STATUS_NUM_SENS,
    // Per-sensor arrays [0 .. MAX_ESF_SENSORS-1]
    DATA_UBX_ESF_STATUS_SENS_TYPE,
    DATA_UBX_ESF_STATUS_SENS_TYPE_X    = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_TYPE),
    DATA_UBX_ESF_STATUS_SENS_USED,
    DATA_UBX_ESF_STATUS_SENS_USED_X    = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_USED),
    DATA_UBX_ESF_STATUS_SENS_READY,
    DATA_UBX_ESF_STATUS_SENS_READY_X   = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_READY),
    DATA_UBX_ESF_STATUS_SENS_CALIB,
    DATA_UBX_ESF_STATUS_SENS_CALIB_X   = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_CALIB),
    DATA_UBX_ESF_STATUS_SENS_TIME_STATUS,
    DATA_UBX_ESF_STATUS_SENS_TIME_STATUS_X = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_TIME_STATUS),
    DATA_UBX_ESF_STATUS_SENS_FREQ,
    DATA_UBX_ESF_STATUS_SENS_FREQ_X    = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_FREQ),
    DATA_UBX_ESF_STATUS_SENS_FAULTS,
    DATA_UBX_ESF_STATUS_SENS_FAULTS_X  = (MAX_ESF_SENSORS + DATA_UBX_ESF_STATUS_SENS_FAULTS),

    // ── UBX-ESF-MEAS ─────────────────────────────────────────────────────────
    DATA_UBX_ESF_MEAS_TIME_TAG,
    DATA_UBX_ESF_MEAS_FLAGS,
    DATA_UBX_ESF_MEAS_NUM_MEAS,
    // Per-measurement arrays [0 .. MAX_ESF_MEAS_DATA-1]
    DATA_UBX_ESF_MEAS_DATA_TYPE,
    DATA_UBX_ESF_MEAS_DATA_TYPE_X      = (MAX_ESF_MEAS_DATA + DATA_UBX_ESF_MEAS_DATA_TYPE),
    DATA_UBX_ESF_MEAS_DATA_VALUE,
    DATA_UBX_ESF_MEAS_DATA_VALUE_X     = (MAX_ESF_MEAS_DATA + DATA_UBX_ESF_MEAS_DATA_VALUE),

    // ── UBX-NAV-SIG ──────────────────────────────────────────────────────────
    DATA_UBX_NAV_SIG_NUM_SIGS,
    // Per-signal arrays [0 .. MAX_ALL_GNSS_SIGNALS-1]
    DATA_UBX_NAV_SIG_GNSSID,
    DATA_UBX_NAV_SIG_GNSSID_X         = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_GNSSID),
    DATA_UBX_NAV_SIG_SVID,
    DATA_UBX_NAV_SIG_SVID_X           = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_SVID),
    DATA_UBX_NAV_SIG_SIGID,
    DATA_UBX_NAV_SIG_SIGID_X          = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_SIGID),
    DATA_UBX_NAV_SIG_FREQID,
    DATA_UBX_NAV_SIG_FREQID_X         = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_FREQID),
    DATA_UBX_NAV_SIG_PR_RES,
    DATA_UBX_NAV_SIG_PR_RES_X         = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_PR_RES),
    DATA_UBX_NAV_SIG_CNO,
    DATA_UBX_NAV_SIG_CNO_X            = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_CNO),
    DATA_UBX_NAV_SIG_QUAL_IND,
    DATA_UBX_NAV_SIG_QUAL_IND_X       = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_QUAL_IND),
    DATA_UBX_NAV_SIG_CORR_SOURCE,
    DATA_UBX_NAV_SIG_CORR_SOURCE_X    = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_CORR_SOURCE),
    DATA_UBX_NAV_SIG_IONO_MODEL,
    DATA_UBX_NAV_SIG_IONO_MODEL_X     = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_IONO_MODEL),
    DATA_UBX_NAV_SIG_HEALTH,
    DATA_UBX_NAV_SIG_HEALTH_X         = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_HEALTH),
    DATA_UBX_NAV_SIG_PR_USED,
    DATA_UBX_NAV_SIG_PR_USED_X        = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_PR_USED),
    DATA_UBX_NAV_SIG_CR_USED,
    DATA_UBX_NAV_SIG_CR_USED_X        = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_CR_USED),
    DATA_UBX_NAV_SIG_DO_USED,
    DATA_UBX_NAV_SIG_DO_USED_X        = (MAX_ALL_GNSS_SIGNALS + DATA_UBX_NAV_SIG_DO_USED),

    // ── UBX-NAV-TIMEUTC ──────────────────────────────────────────────────────
    DATA_UBX_NAV_TIMEUTC_ITOW,
    DATA_UBX_NAV_TIMEUTC_T_ACC,
    DATA_UBX_NAV_TIMEUTC_NANO,
    DATA_UBX_NAV_TIMEUTC_YEAR,
    DATA_UBX_NAV_TIMEUTC_MONTH,
    DATA_UBX_NAV_TIMEUTC_DAY,
    DATA_UBX_NAV_TIMEUTC_HOUR,
    DATA_UBX_NAV_TIMEUTC_MIN,
    DATA_UBX_NAV_TIMEUTC_SEC,
    DATA_UBX_NAV_TIMEUTC_VALID,

    // ── UBX-NAV-CLOCK ────────────────────────────────────────────────────────
    DATA_UBX_NAV_CLOCK_ITOW,
    DATA_UBX_NAV_CLOCK_CLKB,
    DATA_UBX_NAV_CLOCK_CLKD,
    DATA_UBX_NAV_CLOCK_T_ACC,
    DATA_UBX_NAV_CLOCK_F_ACC,

    // ── UBX-NAV-ATT ──────────────────────────────────────────────────────────
    DATA_UBX_NAV_ATT_ITOW,
    DATA_UBX_NAV_ATT_VERSION,
    DATA_UBX_NAV_ATT_ROLL,
    DATA_UBX_NAV_ATT_PITCH,
    DATA_UBX_NAV_ATT_HEADING,
    DATA_UBX_NAV_ATT_ACC_ROLL,
    DATA_UBX_NAV_ATT_ACC_PITCH,
    DATA_UBX_NAV_ATT_ACC_HEADING,

    // ── UBX-RXM-MEASX ────────────────────────────────────────────────────────
    DATA_UBX_RXM_MEASX_GPS_TOW,
    DATA_UBX_RXM_MEASX_GLO_TOW,
    DATA_UBX_RXM_MEASX_BDS_TOW,
    DATA_UBX_RXM_MEASX_QZS_TOW,
    DATA_UBX_RXM_MEASX_GPS_TOW_ACC,
    DATA_UBX_RXM_MEASX_GLO_TOW_ACC,
    DATA_UBX_RXM_MEASX_BDS_TOW_ACC,
    DATA_UBX_RXM_MEASX_QZS_TOW_ACC,
    DATA_UBX_RXM_MEASX_NUM_SV,
    DATA_UBX_RXM_MEASX_FLAGS,
    // Per-SV arrays [0 .. MAX_RXM_MEASX_MEAS-1]
    DATA_UBX_RXM_MEASX_GNSS_ID,
    DATA_UBX_RXM_MEASX_GNSS_ID_X      = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_GNSS_ID),
    DATA_UBX_RXM_MEASX_SV_ID,
    DATA_UBX_RXM_MEASX_SV_ID_X        = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_SV_ID),
    DATA_UBX_RXM_MEASX_CN0,
    DATA_UBX_RXM_MEASX_CN0_X          = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_CN0),
    DATA_UBX_RXM_MEASX_MPH,
    DATA_UBX_RXM_MEASX_MPH_X          = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_MPH),
    DATA_UBX_RXM_MEASX_DOPPLER,
    DATA_UBX_RXM_MEASX_DOPPLER_X      = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_DOPPLER),
    DATA_UBX_RXM_MEASX_WHOLE_CHIPS,
    DATA_UBX_RXM_MEASX_WHOLE_CHIPS_X  = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_WHOLE_CHIPS),
    DATA_UBX_RXM_MEASX_FRAC_CHIPS,
    DATA_UBX_RXM_MEASX_FRAC_CHIPS_X   = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_FRAC_CHIPS),
    DATA_UBX_RXM_MEASX_CODE_PHASE,
    DATA_UBX_RXM_MEASX_CODE_PHASE_X   = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_CODE_PHASE),
    DATA_UBX_RXM_MEASX_INT_CODE_PHASE,
    DATA_UBX_RXM_MEASX_INT_CODE_PHASE_X = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_INT_CODE_PHASE),
    DATA_UBX_RXM_MEASX_PSEU_RANGE_RMS_ERR,
    DATA_UBX_RXM_MEASX_PSEU_RANGE_RMS_ERR_X = (MAX_RXM_MEASX_MEAS + DATA_UBX_RXM_MEASX_PSEU_RANGE_RMS_ERR),

    // ── UBX-MON-IO ───────────────────────────────────────────────────────────
    DATA_UBX_MON_IO_NUM_PORTS,
    // Per-port arrays [0 .. MAX_MON_IO_PORTS-1]
    DATA_UBX_MON_IO_RX_BYTES,
    DATA_UBX_MON_IO_RX_BYTES_X        = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_RX_BYTES),
    DATA_UBX_MON_IO_TX_BYTES,
    DATA_UBX_MON_IO_TX_BYTES_X        = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_TX_BYTES),
    DATA_UBX_MON_IO_PARITY_ERRS,
    DATA_UBX_MON_IO_PARITY_ERRS_X     = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_PARITY_ERRS),
    DATA_UBX_MON_IO_FRAMING_ERRS,
    DATA_UBX_MON_IO_FRAMING_ERRS_X    = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_FRAMING_ERRS),
    DATA_UBX_MON_IO_OVERRUN_ERRS,
    DATA_UBX_MON_IO_OVERRUN_ERRS_X    = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_OVERRUN_ERRS),
    DATA_UBX_MON_IO_BREAK_COND,
    DATA_UBX_MON_IO_BREAK_COND_X      = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_BREAK_COND),
    DATA_UBX_MON_IO_RX_BUSY,
    DATA_UBX_MON_IO_RX_BUSY_X         = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_RX_BUSY),
    DATA_UBX_MON_IO_TX_BUSY,
    DATA_UBX_MON_IO_TX_BUSY_X         = (MAX_MON_IO_PORTS + DATA_UBX_MON_IO_TX_BUSY),

    // ── UBX-MON-TXBUF ────────────────────────────────────────────────────────
    DATA_UBX_MON_TXBUF_ERRORS,
    DATA_UBX_MON_TXBUF_LIMIT,
    DATA_UBX_MON_TXBUF_AVAIL_0,
    DATA_UBX_MON_TXBUF_AVAIL_1,
    DATA_UBX_MON_TXBUF_AVAIL_2,
    DATA_UBX_MON_TXBUF_AVAIL_3,
    DATA_UBX_MON_TXBUF_AVAIL_4,
    DATA_UBX_MON_TXBUF_AVAIL_5,
    DATA_UBX_MON_TXBUF_PENDING_0,
    DATA_UBX_MON_TXBUF_PENDING_1,
    DATA_UBX_MON_TXBUF_PENDING_2,
    DATA_UBX_MON_TXBUF_PENDING_3,
    DATA_UBX_MON_TXBUF_PENDING_4,
    DATA_UBX_MON_TXBUF_PENDING_5,
    DATA_UBX_MON_TXBUF_USAGE_0,
    DATA_UBX_MON_TXBUF_USAGE_1,
    DATA_UBX_MON_TXBUF_USAGE_2,
    DATA_UBX_MON_TXBUF_USAGE_3,
    DATA_UBX_MON_TXBUF_USAGE_4,
    DATA_UBX_MON_TXBUF_USAGE_5,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_0,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_1,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_2,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_3,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_4,
    DATA_UBX_MON_TXBUF_PEAK_USAGE_5,
    DATA_UBX_MON_TXBUF_TUSED,
    DATA_UBX_MON_TXBUF_TPEAK,

    // ── UBX-MON-SPAN ─────────────────────────────────────────────────────────
    DATA_UBX_MON_SPAN_NUM_RF_BLOCKS,
    // Per-RF-block PGA array [0 .. MAX_MON_SPAN_RF_BLOCKS-1]
    DATA_UBX_MON_SPAN_PGA,
    DATA_UBX_MON_SPAN_PGA_X           = (MAX_MON_SPAN_RF_BLOCKS + DATA_UBX_MON_SPAN_PGA),

    // ── UBX-SEC-SIG ──────────────────────────────────────────────────────────
    DATA_UBX_SEC_SIG_VERSION,           ///< Message version (0x01)
    DATA_UBX_SEC_SIG_JAM_FLAGS,         ///< Raw jamFlags byte (X1)
    DATA_UBX_SEC_SIG_JAM_DET_ENABLED,   ///< jamFlags bit 0: jamming detection enabled
    DATA_UBX_SEC_SIG_JAMMING_STATE,     ///< jamFlags bits 2-1: jamming/interference state (0-3)
    DATA_UBX_SEC_SIG_SPF_FLAGS,         ///< Raw spfFlags byte (X1)
    DATA_UBX_SEC_SIG_SPF_DET_ENABLED,   ///< spfFlags bit 0: spoofing detection enabled
    DATA_UBX_SEC_SIG_SPOOFING_STATE,    ///< spfFlags bits 3-1: spoofing state (0-3)

    // ── sentinel / calculated fields ─────────────────────────────────────────
    DATA_PARSE,
    DATA_PARSE_X = DATA_PARSE - 1,

    DATA_NUM  ///< Total number of field slots (must be last).
};

// ── msg_type ──────────────────────────────────────────────────────────────────
// Identifies the UBX (or NMEA) message that just arrived.  Used as the epoch
// trigger key and as the bit-position in the message mask.
// Values are kept identical to the old CDatabase::MSG_t.

enum msg_type : uint8_t
{
    MSG_UNKNOWN            = 0,
    MSG_NMEA_GBS,
    MSG_NMEA_GGA,
    MSG_NMEA_GLL,
    MSG_NMEA_GNS,
    MSG_NMEA_GRS,
    MSG_NMEA_GSA,
    MSG_NMEA_GST,
    MSG_NMEA_GSV,
    MSG_NMEA_RMC,
    MSG_NMEA_VTG,
    MSG_NMEA_ZDA,
    MSG_UBX_NAV_PVT,
    MSG_UBX_NAV_PVAT,
    MSG_UBX_NAV_DOP,
    MSG_UBX_NAV_EELL,
    MSG_UBX_NAV_TIMEGPS,
    MSG_UBX_NAV_EOE,
    MSG_UBX_NAV_ODO,
    MSG_UBX_NAV2_PVT,
    MSG_UBX_NAV2_DOP,
    MSG_UBX_NAV2_EELL,
    MSG_UBX_NAV2_TIMEGPS,
    MSG_UBX_NAV2_EOE,
    MSG_UBX_ESF_INS,
    MSG_UBX_ESF_MEAS,
    MSG_UBX_ESF_STATUS,
    MSG_UBX_TIM_TP,
    MSG_UBX_NAV_SAT,
    MSG_UBX_NAV_SIG,
    MSG_UBX_SEC_CRC,
    MSG_UBX_SEC_SIG,
    MSG_UBX_NAV_STATUS,
    MSG_UBX_RXM_MEAS,
    MSG_UBX_MON_RF,
    MSG_UBX_MON_VER,
    MSG_UBX_INF_ERR,
    MSG_UBX_INF_DBG,
    MSG_UBX_ACK_ACK,
    MSG_UBX_ACK_NAK,
    MSG_UBX_CFG_VALGET,
    MSG_UBX_CFG_VALSET,
    MSG_UBX_NAV_TIMEUTC,
    MSG_UBX_NAV_CLOCK,
    MSG_UBX_NAV_ATT,
    MSG_UBX_RXM_MEASX,
    MSG_UBX_MON_IO,
    MSG_UBX_MON_TXBUF,
    MSG_UBX_MON_SPAN,
    MSG_NUM  ///< Sentinel – must be last; also signals "not set".
};

// ── Helper: safe offset into an array-field base ──────────────────────────────

inline data_field db_index_with_offset(data_field base, uint8_t offset)
{
    uint16_t idx = static_cast<uint16_t>(base) + static_cast<uint16_t>(offset);
    if (idx < static_cast<uint16_t>(DATA_PARSE))
    {
        return static_cast<data_field>(idx);
    }
    return DATA_PARSE;
}

} // namespace database
} // namespace ubx
