// MIT License
//
// Copyright (c) 2026 nguyenchiemminhvu
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// Static lookup table — all key IDs imported from ubx_config_key.h.
// Generated from the official u-blox ubxlib source (lines 2248-3207).
// DO NOT hand-edit the table entries; regenerate from ubx_config_key.h.

#include "config/ubx_cfg_key_registry.h"
#include "config/ubx_config_key.h"
#include <cstring>

namespace ubx
{
namespace config
{

#define KEY_ENTRY(sym) { #sym, cfg_key::sym }

static const key_info s_key_table[] = {
    // ANA
    KEY_ENTRY(ana_use_ana),
    KEY_ENTRY(ana_orbmaxerr),

    // BATCH
    KEY_ENTRY(batch_enable),
    KEY_ENTRY(batch_pioenable),
    KEY_ENTRY(batch_maxentries),
    KEY_ENTRY(batch_warnthrs),
    KEY_ENTRY(batch_pioactivelow),
    KEY_ENTRY(batch_pioid),
    KEY_ENTRY(batch_extrapvt),
    KEY_ENTRY(batch_extraodo),

    // BDS
    KEY_ENTRY(bds_use_geo_prn),

    // GEOFENCE
    KEY_ENTRY(geofence_conflvl),
    KEY_ENTRY(geofence_use_pio),
    KEY_ENTRY(geofence_pinpol),
    KEY_ENTRY(geofence_pin),
    KEY_ENTRY(geofence_use_fence1),
    KEY_ENTRY(geofence_fence1_lat),
    KEY_ENTRY(geofence_fence1_lon),
    KEY_ENTRY(geofence_fence1_rad),
    KEY_ENTRY(geofence_use_fence2),
    KEY_ENTRY(geofence_fence2_lat),
    KEY_ENTRY(geofence_fence2_lon),
    KEY_ENTRY(geofence_fence2_rad),
    KEY_ENTRY(geofence_use_fence3),
    KEY_ENTRY(geofence_fence3_lat),
    KEY_ENTRY(geofence_fence3_lon),
    KEY_ENTRY(geofence_fence3_rad),
    KEY_ENTRY(geofence_use_fence4),
    KEY_ENTRY(geofence_fence4_lat),
    KEY_ENTRY(geofence_fence4_lon),
    KEY_ENTRY(geofence_fence4_rad),

    // HW
    KEY_ENTRY(hw_ant_cfg_voltctrl),
    KEY_ENTRY(hw_ant_cfg_shortdet),
    KEY_ENTRY(hw_ant_cfg_shortdet_pol),
    KEY_ENTRY(hw_ant_cfg_opendet),
    KEY_ENTRY(hw_ant_cfg_opendet_pol),
    KEY_ENTRY(hw_ant_cfg_pwrdown),
    KEY_ENTRY(hw_ant_cfg_pwrdown_pol),
    KEY_ENTRY(hw_ant_cfg_recover),
    KEY_ENTRY(hw_ant_sup_switch_pin),
    KEY_ENTRY(hw_ant_sup_short_pin),
    KEY_ENTRY(hw_ant_sup_open_pin),
    KEY_ENTRY(hw_ant_sup_engine),
    KEY_ENTRY(hw_ant_sup_short_thr),
    KEY_ENTRY(hw_ant_sup_open_thr),
    KEY_ENTRY(hw_rf_lna_mode),

    // I2C
    KEY_ENTRY(i2c_address),
    KEY_ENTRY(i2c_extendedtimeout),
    KEY_ENTRY(i2c_enabled),

    // I2CINPROT
    KEY_ENTRY(i2cinprot_ubx),
    KEY_ENTRY(i2cinprot_nmea),
    KEY_ENTRY(i2cinprot_rtcm3x),
    KEY_ENTRY(i2cinprot_spartn),

    // I2COUTPROT
    KEY_ENTRY(i2coutprot_ubx),
    KEY_ENTRY(i2coutprot_nmea),
    KEY_ENTRY(i2coutprot_rtcm3x),

    // INFMSG
    KEY_ENTRY(infmsg_ubx_i2c),
    KEY_ENTRY(infmsg_ubx_uart1),
    KEY_ENTRY(infmsg_ubx_uart2),
    KEY_ENTRY(infmsg_ubx_usb),
    KEY_ENTRY(infmsg_ubx_spi),
    KEY_ENTRY(infmsg_nmea_i2c),
    KEY_ENTRY(infmsg_nmea_uart1),
    KEY_ENTRY(infmsg_nmea_uart2),
    KEY_ENTRY(infmsg_nmea_usb),
    KEY_ENTRY(infmsg_nmea_spi),

    // ITFM
    KEY_ENTRY(itfm_bbthreshold),
    KEY_ENTRY(itfm_cwthreshold),
    KEY_ENTRY(itfm_enable),
    KEY_ENTRY(itfm_antsetting),
    KEY_ENTRY(itfm_enable_aux),

    // LOGFILTER
    KEY_ENTRY(logfilter_record_ena),
    KEY_ENTRY(logfilter_once_per_wake_up_ena),
    KEY_ENTRY(logfilter_apply_all_filters),
    KEY_ENTRY(logfilter_min_interval),
    KEY_ENTRY(logfilter_time_thrs),
    KEY_ENTRY(logfilter_speed_thrs),
    KEY_ENTRY(logfilter_position_thrs),

    // MOT
    KEY_ENTRY(mot_gnssspeed_thrs),
    KEY_ENTRY(mot_gnssdist_thrs),

    // MSGOUT — NMEA
    KEY_ENTRY(msgout_nmea_id_dtm_i2c),
    KEY_ENTRY(msgout_nmea_id_dtm_spi),
    KEY_ENTRY(msgout_nmea_id_dtm_uart1),
    KEY_ENTRY(msgout_nmea_id_dtm_uart2),
    KEY_ENTRY(msgout_nmea_id_dtm_usb),
    KEY_ENTRY(msgout_nmea_id_gbs_i2c),
    KEY_ENTRY(msgout_nmea_id_gbs_spi),
    KEY_ENTRY(msgout_nmea_id_gbs_uart1),
    KEY_ENTRY(msgout_nmea_id_gbs_uart2),
    KEY_ENTRY(msgout_nmea_id_gbs_usb),
    KEY_ENTRY(msgout_nmea_id_gga_i2c),
    KEY_ENTRY(msgout_nmea_id_gga_spi),
    KEY_ENTRY(msgout_nmea_id_gga_uart1),
    KEY_ENTRY(msgout_nmea_id_gga_uart2),
    KEY_ENTRY(msgout_nmea_id_gga_usb),
    KEY_ENTRY(msgout_nmea_id_gll_i2c),
    KEY_ENTRY(msgout_nmea_id_gll_spi),
    KEY_ENTRY(msgout_nmea_id_gll_uart1),
    KEY_ENTRY(msgout_nmea_id_gll_uart2),
    KEY_ENTRY(msgout_nmea_id_gll_usb),
    KEY_ENTRY(msgout_nmea_id_gns_i2c),
    KEY_ENTRY(msgout_nmea_id_gns_spi),
    KEY_ENTRY(msgout_nmea_id_gns_uart1),
    KEY_ENTRY(msgout_nmea_id_gns_uart2),
    KEY_ENTRY(msgout_nmea_id_gns_usb),
    KEY_ENTRY(msgout_nmea_id_grs_i2c),
    KEY_ENTRY(msgout_nmea_id_grs_spi),
    KEY_ENTRY(msgout_nmea_id_grs_uart1),
    KEY_ENTRY(msgout_nmea_id_grs_uart2),
    KEY_ENTRY(msgout_nmea_id_grs_usb),
    KEY_ENTRY(msgout_nmea_id_gsa_i2c),
    KEY_ENTRY(msgout_nmea_id_gsa_spi),
    KEY_ENTRY(msgout_nmea_id_gsa_uart1),
    KEY_ENTRY(msgout_nmea_id_gsa_uart2),
    KEY_ENTRY(msgout_nmea_id_gsa_usb),
    KEY_ENTRY(msgout_nmea_id_gst_i2c),
    KEY_ENTRY(msgout_nmea_id_gst_spi),
    KEY_ENTRY(msgout_nmea_id_gst_uart1),
    KEY_ENTRY(msgout_nmea_id_gst_uart2),
    KEY_ENTRY(msgout_nmea_id_gst_usb),
    KEY_ENTRY(msgout_nmea_id_gsv_i2c),
    KEY_ENTRY(msgout_nmea_id_gsv_spi),
    KEY_ENTRY(msgout_nmea_id_gsv_uart1),
    KEY_ENTRY(msgout_nmea_id_gsv_uart2),
    KEY_ENTRY(msgout_nmea_id_gsv_usb),
    KEY_ENTRY(msgout_nmea_id_rlm_i2c),
    KEY_ENTRY(msgout_nmea_id_rlm_spi),
    KEY_ENTRY(msgout_nmea_id_rlm_uart1),
    KEY_ENTRY(msgout_nmea_id_rlm_uart2),
    KEY_ENTRY(msgout_nmea_id_rlm_usb),
    KEY_ENTRY(msgout_nmea_id_rmc_i2c),
    KEY_ENTRY(msgout_nmea_id_rmc_spi),
    KEY_ENTRY(msgout_nmea_id_rmc_uart1),
    KEY_ENTRY(msgout_nmea_id_rmc_uart2),
    KEY_ENTRY(msgout_nmea_id_rmc_usb),
    KEY_ENTRY(msgout_nmea_id_vlw_i2c),
    KEY_ENTRY(msgout_nmea_id_vlw_spi),
    KEY_ENTRY(msgout_nmea_id_vlw_uart1),
    KEY_ENTRY(msgout_nmea_id_vlw_uart2),
    KEY_ENTRY(msgout_nmea_id_vlw_usb),
    KEY_ENTRY(msgout_nmea_id_vtg_i2c),
    KEY_ENTRY(msgout_nmea_id_vtg_spi),
    KEY_ENTRY(msgout_nmea_id_vtg_uart1),
    KEY_ENTRY(msgout_nmea_id_vtg_uart2),
    KEY_ENTRY(msgout_nmea_id_vtg_usb),
    KEY_ENTRY(msgout_nmea_id_zda_i2c),
    KEY_ENTRY(msgout_nmea_id_zda_spi),
    KEY_ENTRY(msgout_nmea_id_zda_uart1),
    KEY_ENTRY(msgout_nmea_id_zda_uart2),
    KEY_ENTRY(msgout_nmea_id_zda_usb),

    // MSGOUT — NMEA NAV2
    KEY_ENTRY(msgout_nmea_nav2_id_gga_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_gga_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_gga_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_gga_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_gga_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_gll_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_gll_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_gll_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_gll_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_gll_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_gns_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_gns_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_gns_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_gns_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_gns_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_gsa_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_gsa_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_gsa_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_gsa_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_gsa_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_rmc_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_rmc_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_rmc_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_rmc_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_rmc_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_vtg_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_vtg_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_vtg_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_vtg_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_vtg_usb),
    KEY_ENTRY(msgout_nmea_nav2_id_zda_i2c),
    KEY_ENTRY(msgout_nmea_nav2_id_zda_spi),
    KEY_ENTRY(msgout_nmea_nav2_id_zda_uart1),
    KEY_ENTRY(msgout_nmea_nav2_id_zda_uart2),
    KEY_ENTRY(msgout_nmea_nav2_id_zda_usb),

    // MSGOUT — PUBX
    KEY_ENTRY(msgout_pubx_id_polyp_i2c),
    KEY_ENTRY(msgout_pubx_id_polyp_spi),
    KEY_ENTRY(msgout_pubx_id_polyp_uart1),
    KEY_ENTRY(msgout_pubx_id_polyp_uart2),
    KEY_ENTRY(msgout_pubx_id_polyp_usb),
    KEY_ENTRY(msgout_pubx_id_polys_i2c),
    KEY_ENTRY(msgout_pubx_id_polys_spi),
    KEY_ENTRY(msgout_pubx_id_polys_uart1),
    KEY_ENTRY(msgout_pubx_id_polys_uart2),
    KEY_ENTRY(msgout_pubx_id_polys_usb),
    KEY_ENTRY(msgout_pubx_id_polyt_i2c),
    KEY_ENTRY(msgout_pubx_id_polyt_spi),
    KEY_ENTRY(msgout_pubx_id_polyt_uart1),
    KEY_ENTRY(msgout_pubx_id_polyt_uart2),
    KEY_ENTRY(msgout_pubx_id_polyt_usb),

    // MSGOUT — RTCM
    KEY_ENTRY(msgout_rtcm_3x_type1005_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1005_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1005_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1005_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1005_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1074_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1074_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1074_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1074_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1074_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1077_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1077_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1077_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1077_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1077_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1084_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1084_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1084_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1084_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1084_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1087_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1087_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1087_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1087_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1087_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1094_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1094_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1094_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1094_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1094_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1097_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1097_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1097_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1097_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1097_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1124_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1124_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1124_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1124_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1124_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1127_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1127_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1127_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1127_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1127_usb),
    KEY_ENTRY(msgout_rtcm_3x_type1230_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type1230_spi),
    KEY_ENTRY(msgout_rtcm_3x_type1230_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type1230_uart2),
    KEY_ENTRY(msgout_rtcm_3x_type1230_usb),
    KEY_ENTRY(msgout_rtcm_3x_type4072_0_i2c),
    KEY_ENTRY(msgout_rtcm_3x_type4072_0_spi),
    KEY_ENTRY(msgout_rtcm_3x_type4072_0_uart1),
    KEY_ENTRY(msgout_rtcm_3x_type4072_0_uart2),

    // MSGOUT — UBX ESF
    KEY_ENTRY(msgout_ubx_esf_alg_i2c),
    KEY_ENTRY(msgout_ubx_esf_alg_spi),
    KEY_ENTRY(msgout_ubx_esf_alg_uart1),
    KEY_ENTRY(msgout_ubx_esf_alg_uart2),
    KEY_ENTRY(msgout_ubx_esf_alg_usb),
    KEY_ENTRY(msgout_ubx_esf_ins_i2c),
    KEY_ENTRY(msgout_ubx_esf_ins_spi),
    KEY_ENTRY(msgout_ubx_esf_ins_uart1),
    KEY_ENTRY(msgout_ubx_esf_ins_uart2),
    KEY_ENTRY(msgout_ubx_esf_ins_usb),
    KEY_ENTRY(msgout_ubx_esf_meas_i2c),
    KEY_ENTRY(msgout_ubx_esf_meas_spi),
    KEY_ENTRY(msgout_ubx_esf_meas_uart1),
    KEY_ENTRY(msgout_ubx_esf_meas_uart2),
    KEY_ENTRY(msgout_ubx_esf_meas_usb),
    KEY_ENTRY(msgout_ubx_esf_raw_i2c),
    KEY_ENTRY(msgout_ubx_esf_raw_spi),
    KEY_ENTRY(msgout_ubx_esf_raw_uart1),
    KEY_ENTRY(msgout_ubx_esf_raw_uart2),
    KEY_ENTRY(msgout_ubx_esf_raw_usb),
    KEY_ENTRY(msgout_ubx_esf_status_i2c),
    KEY_ENTRY(msgout_ubx_esf_status_spi),
    KEY_ENTRY(msgout_ubx_esf_status_uart1),
    KEY_ENTRY(msgout_ubx_esf_status_uart2),
    KEY_ENTRY(msgout_ubx_esf_status_usb),

    // MSGOUT — UBX LOG
    KEY_ENTRY(msgout_ubx_log_info_i2c),
    KEY_ENTRY(msgout_ubx_log_info_spi),
    KEY_ENTRY(msgout_ubx_log_info_uart1),
    KEY_ENTRY(msgout_ubx_log_info_uart2),
    KEY_ENTRY(msgout_ubx_log_info_usb),

    // MSGOUT — UBX MON
    KEY_ENTRY(msgout_ubx_mon_comms_i2c),
    KEY_ENTRY(msgout_ubx_mon_comms_spi),
    KEY_ENTRY(msgout_ubx_mon_comms_uart1),
    KEY_ENTRY(msgout_ubx_mon_comms_uart2),
    KEY_ENTRY(msgout_ubx_mon_comms_usb),
    KEY_ENTRY(msgout_ubx_mon_hw2_i2c),
    KEY_ENTRY(msgout_ubx_mon_hw2_spi),
    KEY_ENTRY(msgout_ubx_mon_hw2_uart1),
    KEY_ENTRY(msgout_ubx_mon_hw2_uart2),
    KEY_ENTRY(msgout_ubx_mon_hw2_usb),
    KEY_ENTRY(msgout_ubx_mon_hw3_i2c),
    KEY_ENTRY(msgout_ubx_mon_hw3_spi),
    KEY_ENTRY(msgout_ubx_mon_hw3_uart1),
    KEY_ENTRY(msgout_ubx_mon_hw3_uart2),
    KEY_ENTRY(msgout_ubx_mon_hw3_usb),
    KEY_ENTRY(msgout_ubx_mon_hw_i2c),
    KEY_ENTRY(msgout_ubx_mon_hw_spi),
    KEY_ENTRY(msgout_ubx_mon_hw_uart1),
    KEY_ENTRY(msgout_ubx_mon_hw_uart2),
    KEY_ENTRY(msgout_ubx_mon_hw_usb),
    KEY_ENTRY(msgout_ubx_mon_io_i2c),
    KEY_ENTRY(msgout_ubx_mon_io_spi),
    KEY_ENTRY(msgout_ubx_mon_io_uart1),
    KEY_ENTRY(msgout_ubx_mon_io_uart2),
    KEY_ENTRY(msgout_ubx_mon_io_usb),
    KEY_ENTRY(msgout_ubx_mon_msgpp_i2c),
    KEY_ENTRY(msgout_ubx_mon_msgpp_spi),
    KEY_ENTRY(msgout_ubx_mon_msgpp_uart1),
    KEY_ENTRY(msgout_ubx_mon_msgpp_uart2),
    KEY_ENTRY(msgout_ubx_mon_msgpp_usb),
    KEY_ENTRY(msgout_ubx_mon_rf_i2c),
    KEY_ENTRY(msgout_ubx_mon_rf_spi),
    KEY_ENTRY(msgout_ubx_mon_rf_uart1),
    KEY_ENTRY(msgout_ubx_mon_rf_uart2),
    KEY_ENTRY(msgout_ubx_mon_rf_usb),
    KEY_ENTRY(msgout_ubx_mon_rxbuf_i2c),
    KEY_ENTRY(msgout_ubx_mon_rxbuf_spi),
    KEY_ENTRY(msgout_ubx_mon_rxbuf_uart1),
    KEY_ENTRY(msgout_ubx_mon_rxbuf_uart2),
    KEY_ENTRY(msgout_ubx_mon_rxbuf_usb),
    KEY_ENTRY(msgout_ubx_mon_rxr_i2c),
    KEY_ENTRY(msgout_ubx_mon_rxr_spi),
    KEY_ENTRY(msgout_ubx_mon_rxr_uart1),
    KEY_ENTRY(msgout_ubx_mon_rxr_uart2),
    KEY_ENTRY(msgout_ubx_mon_rxr_usb),
    KEY_ENTRY(msgout_ubx_mon_span_i2c),
    KEY_ENTRY(msgout_ubx_mon_span_spi),
    KEY_ENTRY(msgout_ubx_mon_span_uart1),
    KEY_ENTRY(msgout_ubx_mon_span_uart2),
    KEY_ENTRY(msgout_ubx_mon_span_usb),
    KEY_ENTRY(msgout_ubx_mon_sys_i2c),
    KEY_ENTRY(msgout_ubx_mon_sys_spi),
    KEY_ENTRY(msgout_ubx_mon_sys_uart1),
    KEY_ENTRY(msgout_ubx_mon_sys_uart2),
    KEY_ENTRY(msgout_ubx_mon_sys_usb),
    KEY_ENTRY(msgout_ubx_mon_txbuf_i2c),
    KEY_ENTRY(msgout_ubx_mon_txbuf_spi),
    KEY_ENTRY(msgout_ubx_mon_txbuf_uart1),
    KEY_ENTRY(msgout_ubx_mon_txbuf_uart2),
    KEY_ENTRY(msgout_ubx_mon_txbuf_usb),

    // MSGOUT — UBX NAV2
    KEY_ENTRY(msgout_ubx_nav2_clock_i2c),
    KEY_ENTRY(msgout_ubx_nav2_clock_spi),
    KEY_ENTRY(msgout_ubx_nav2_clock_uart1),
    KEY_ENTRY(msgout_ubx_nav2_clock_uart2),
    KEY_ENTRY(msgout_ubx_nav2_clock_usb),
    KEY_ENTRY(msgout_ubx_nav2_cov_i2c),
    KEY_ENTRY(msgout_ubx_nav2_cov_spi),
    KEY_ENTRY(msgout_ubx_nav2_cov_uart1),
    KEY_ENTRY(msgout_ubx_nav2_cov_uart2),
    KEY_ENTRY(msgout_ubx_nav2_cov_usb),
    KEY_ENTRY(msgout_ubx_nav2_dop_i2c),
    KEY_ENTRY(msgout_ubx_nav2_dop_spi),
    KEY_ENTRY(msgout_ubx_nav2_dop_uart1),
    KEY_ENTRY(msgout_ubx_nav2_dop_uart2),
    KEY_ENTRY(msgout_ubx_nav2_dop_usb),
    KEY_ENTRY(msgout_ubx_nav2_eoe_i2c),
    KEY_ENTRY(msgout_ubx_nav2_eoe_spi),
    KEY_ENTRY(msgout_ubx_nav2_eoe_uart1),
    KEY_ENTRY(msgout_ubx_nav2_eoe_uart2),
    KEY_ENTRY(msgout_ubx_nav2_eoe_usb),
    KEY_ENTRY(msgout_ubx_nav2_odo_i2c),
    KEY_ENTRY(msgout_ubx_nav2_odo_spi),
    KEY_ENTRY(msgout_ubx_nav2_odo_uart1),
    KEY_ENTRY(msgout_ubx_nav2_odo_uart2),
    KEY_ENTRY(msgout_ubx_nav2_odo_usb),
    KEY_ENTRY(msgout_ubx_nav2_posecef_i2c),
    KEY_ENTRY(msgout_ubx_nav2_posecef_spi),
    KEY_ENTRY(msgout_ubx_nav2_posecef_uart1),
    KEY_ENTRY(msgout_ubx_nav2_posecef_uart2),
    KEY_ENTRY(msgout_ubx_nav2_posecef_usb),
    KEY_ENTRY(msgout_ubx_nav2_posllh_i2c),
    KEY_ENTRY(msgout_ubx_nav2_posllh_spi),
    KEY_ENTRY(msgout_ubx_nav2_posllh_uart1),
    KEY_ENTRY(msgout_ubx_nav2_posllh_uart2),
    KEY_ENTRY(msgout_ubx_nav2_posllh_usb),
    KEY_ENTRY(msgout_ubx_nav2_pvt_i2c),
    KEY_ENTRY(msgout_ubx_nav2_pvt_spi),
    KEY_ENTRY(msgout_ubx_nav2_pvt_uart1),
    KEY_ENTRY(msgout_ubx_nav2_pvt_uart2),
    KEY_ENTRY(msgout_ubx_nav2_pvt_usb),
    KEY_ENTRY(msgout_ubx_nav2_sat_i2c),
    KEY_ENTRY(msgout_ubx_nav2_sat_spi),
    KEY_ENTRY(msgout_ubx_nav2_sat_uart1),
    KEY_ENTRY(msgout_ubx_nav2_sat_uart2),
    KEY_ENTRY(msgout_ubx_nav2_sat_usb),
    KEY_ENTRY(msgout_ubx_nav2_sbas_i2c),
    KEY_ENTRY(msgout_ubx_nav2_sbas_spi),
    KEY_ENTRY(msgout_ubx_nav2_sbas_uart1),
    KEY_ENTRY(msgout_ubx_nav2_sbas_uart2),
    KEY_ENTRY(msgout_ubx_nav2_sbas_usb),
    KEY_ENTRY(msgout_ubx_nav2_sig_i2c),
    KEY_ENTRY(msgout_ubx_nav2_sig_spi),
    KEY_ENTRY(msgout_ubx_nav2_sig_uart1),
    KEY_ENTRY(msgout_ubx_nav2_sig_uart2),
    KEY_ENTRY(msgout_ubx_nav2_sig_usb),
    KEY_ENTRY(msgout_ubx_nav2_slas_i2c),
    KEY_ENTRY(msgout_ubx_nav2_slas_spi),
    KEY_ENTRY(msgout_ubx_nav2_slas_uart1),
    KEY_ENTRY(msgout_ubx_nav2_slas_uart2),
    KEY_ENTRY(msgout_ubx_nav2_slas_usb),
    KEY_ENTRY(msgout_ubx_nav2_status_i2c),
    KEY_ENTRY(msgout_ubx_nav2_status_spi),
    KEY_ENTRY(msgout_ubx_nav2_status_uart1),
    KEY_ENTRY(msgout_ubx_nav2_status_uart2),
    KEY_ENTRY(msgout_ubx_nav2_status_usb),
    KEY_ENTRY(msgout_ubx_nav2_svin_i2c),
    KEY_ENTRY(msgout_ubx_nav2_svin_spi),
    KEY_ENTRY(msgout_ubx_nav2_svin_uart1),
    KEY_ENTRY(msgout_ubx_nav2_svin_uart2),
    KEY_ENTRY(msgout_ubx_nav2_svin_usb),
    KEY_ENTRY(msgout_ubx_nav2_timebds_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timebds_spi),
    KEY_ENTRY(msgout_ubx_nav2_timebds_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timebds_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timebds_usb),
    KEY_ENTRY(msgout_ubx_nav2_timegal_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timegal_spi),
    KEY_ENTRY(msgout_ubx_nav2_timegal_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timegal_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timegal_usb),
    KEY_ENTRY(msgout_ubx_nav2_timeglo_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timeglo_spi),
    KEY_ENTRY(msgout_ubx_nav2_timeglo_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timeglo_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timeglo_usb),
    KEY_ENTRY(msgout_ubx_nav2_timegps_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timegps_spi),
    KEY_ENTRY(msgout_ubx_nav2_timegps_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timegps_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timegps_usb),
    KEY_ENTRY(msgout_ubx_nav2_timels_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timels_spi),
    KEY_ENTRY(msgout_ubx_nav2_timels_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timels_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timels_usb),
    KEY_ENTRY(msgout_ubx_nav2_timeqzss_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timeqzss_spi),
    KEY_ENTRY(msgout_ubx_nav2_timeqzss_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timeqzss_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timeqzss_usb),
    KEY_ENTRY(msgout_ubx_nav2_timeutc_i2c),
    KEY_ENTRY(msgout_ubx_nav2_timeutc_spi),
    KEY_ENTRY(msgout_ubx_nav2_timeutc_uart1),
    KEY_ENTRY(msgout_ubx_nav2_timeutc_uart2),
    KEY_ENTRY(msgout_ubx_nav2_timeutc_usb),
    KEY_ENTRY(msgout_ubx_nav2_velecef_i2c),
    KEY_ENTRY(msgout_ubx_nav2_velecef_spi),
    KEY_ENTRY(msgout_ubx_nav2_velecef_uart1),
    KEY_ENTRY(msgout_ubx_nav2_velecef_uart2),
    KEY_ENTRY(msgout_ubx_nav2_velecef_usb),
    KEY_ENTRY(msgout_ubx_nav2_velned_i2c),
    KEY_ENTRY(msgout_ubx_nav2_velned_spi),
    KEY_ENTRY(msgout_ubx_nav2_velned_uart1),
    KEY_ENTRY(msgout_ubx_nav2_velned_uart2),
    KEY_ENTRY(msgout_ubx_nav2_velned_usb),

    // MSGOUT — UBX NAV
    KEY_ENTRY(msgout_ubx_nav_att_i2c),
    KEY_ENTRY(msgout_ubx_nav_att_spi),
    KEY_ENTRY(msgout_ubx_nav_att_uart1),
    KEY_ENTRY(msgout_ubx_nav_att_uart2),
    KEY_ENTRY(msgout_ubx_nav_att_usb),
    KEY_ENTRY(msgout_ubx_nav_aopstatus_i2c),
    KEY_ENTRY(msgout_ubx_nav_aopstatus_spi),
    KEY_ENTRY(msgout_ubx_nav_aopstatus_uart1),
    KEY_ENTRY(msgout_ubx_nav_aopstatus_uart2),
    KEY_ENTRY(msgout_ubx_nav_aopstatus_usb),
    KEY_ENTRY(msgout_ubx_nav_clock_i2c),
    KEY_ENTRY(msgout_ubx_nav_clock_spi),
    KEY_ENTRY(msgout_ubx_nav_clock_uart1),
    KEY_ENTRY(msgout_ubx_nav_clock_uart2),
    KEY_ENTRY(msgout_ubx_nav_clock_usb),
    KEY_ENTRY(msgout_ubx_nav_cov_i2c),
    KEY_ENTRY(msgout_ubx_nav_cov_spi),
    KEY_ENTRY(msgout_ubx_nav_cov_uart1),
    KEY_ENTRY(msgout_ubx_nav_cov_uart2),
    KEY_ENTRY(msgout_ubx_nav_cov_usb),
    KEY_ENTRY(msgout_ubx_nav_dop_i2c),
    KEY_ENTRY(msgout_ubx_nav_dop_spi),
    KEY_ENTRY(msgout_ubx_nav_dop_uart1),
    KEY_ENTRY(msgout_ubx_nav_dop_uart2),
    KEY_ENTRY(msgout_ubx_nav_dop_usb),
    KEY_ENTRY(msgout_ubx_nav_eell_i2c),
    KEY_ENTRY(msgout_ubx_nav_eell_spi),
    KEY_ENTRY(msgout_ubx_nav_eell_uart1),
    KEY_ENTRY(msgout_ubx_nav_eell_uart2),
    KEY_ENTRY(msgout_ubx_nav_eell_usb),
    KEY_ENTRY(msgout_ubx_nav_eoe_i2c),
    KEY_ENTRY(msgout_ubx_nav_eoe_spi),
    KEY_ENTRY(msgout_ubx_nav_eoe_uart1),
    KEY_ENTRY(msgout_ubx_nav_eoe_uart2),
    KEY_ENTRY(msgout_ubx_nav_eoe_usb),
    KEY_ENTRY(msgout_ubx_nav_geofence_i2c),
    KEY_ENTRY(msgout_ubx_nav_geofence_spi),
    KEY_ENTRY(msgout_ubx_nav_geofence_uart1),
    KEY_ENTRY(msgout_ubx_nav_geofence_uart2),
    KEY_ENTRY(msgout_ubx_nav_geofence_usb),
    KEY_ENTRY(msgout_ubx_nav_hpposecef_i2c),
    KEY_ENTRY(msgout_ubx_nav_hpposecef_spi),
    KEY_ENTRY(msgout_ubx_nav_hpposecef_uart1),
    KEY_ENTRY(msgout_ubx_nav_hpposecef_uart2),
    KEY_ENTRY(msgout_ubx_nav_hpposecef_usb),
    KEY_ENTRY(msgout_ubx_nav_hpposllh_i2c),
    KEY_ENTRY(msgout_ubx_nav_hpposllh_spi),
    KEY_ENTRY(msgout_ubx_nav_hpposllh_uart1),
    KEY_ENTRY(msgout_ubx_nav_hpposllh_uart2),
    KEY_ENTRY(msgout_ubx_nav_hpposllh_usb),
    KEY_ENTRY(msgout_ubx_nav_odo_i2c),
    KEY_ENTRY(msgout_ubx_nav_odo_spi),
    KEY_ENTRY(msgout_ubx_nav_odo_uart1),
    KEY_ENTRY(msgout_ubx_nav_odo_uart2),
    KEY_ENTRY(msgout_ubx_nav_odo_usb),
    KEY_ENTRY(msgout_ubx_nav_orb_i2c),
    KEY_ENTRY(msgout_ubx_nav_orb_spi),
    KEY_ENTRY(msgout_ubx_nav_orb_uart1),
    KEY_ENTRY(msgout_ubx_nav_orb_uart2),
    KEY_ENTRY(msgout_ubx_nav_orb_usb),
    KEY_ENTRY(msgout_ubx_nav_pl_i2c),
    KEY_ENTRY(msgout_ubx_nav_pl_spi),
    KEY_ENTRY(msgout_ubx_nav_pl_uart1),
    KEY_ENTRY(msgout_ubx_nav_pl_uart2),
    KEY_ENTRY(msgout_ubx_nav_pl_usb),
    KEY_ENTRY(msgout_ubx_nav_posecef_i2c),
    KEY_ENTRY(msgout_ubx_nav_posecef_spi),
    KEY_ENTRY(msgout_ubx_nav_posecef_uart1),
    KEY_ENTRY(msgout_ubx_nav_posecef_uart2),
    KEY_ENTRY(msgout_ubx_nav_posecef_usb),
    KEY_ENTRY(msgout_ubx_nav_posllh_i2c),
    KEY_ENTRY(msgout_ubx_nav_posllh_spi),
    KEY_ENTRY(msgout_ubx_nav_posllh_uart1),
    KEY_ENTRY(msgout_ubx_nav_posllh_uart2),
    KEY_ENTRY(msgout_ubx_nav_posllh_usb),
    KEY_ENTRY(msgout_ubx_nav_pvt_i2c),
    KEY_ENTRY(msgout_ubx_nav_pvt_spi),
    KEY_ENTRY(msgout_ubx_nav_pvt_uart1),
    KEY_ENTRY(msgout_ubx_nav_pvt_uart2),
    KEY_ENTRY(msgout_ubx_nav_pvt_usb),
    KEY_ENTRY(msgout_ubx_nav_relposned_i2c),
    KEY_ENTRY(msgout_ubx_nav_relposned_spi),
    KEY_ENTRY(msgout_ubx_nav_relposned_uart1),
    KEY_ENTRY(msgout_ubx_nav_relposned_uart2),
    KEY_ENTRY(msgout_ubx_nav_relposned_usb),
    KEY_ENTRY(msgout_ubx_nav_sat_i2c),
    KEY_ENTRY(msgout_ubx_nav_sat_spi),
    KEY_ENTRY(msgout_ubx_nav_sat_uart1),
    KEY_ENTRY(msgout_ubx_nav_sat_uart2),
    KEY_ENTRY(msgout_ubx_nav_sat_usb),
    KEY_ENTRY(msgout_ubx_nav_sbas_i2c),
    KEY_ENTRY(msgout_ubx_nav_sbas_spi),
    KEY_ENTRY(msgout_ubx_nav_sbas_uart1),
    KEY_ENTRY(msgout_ubx_nav_sbas_uart2),
    KEY_ENTRY(msgout_ubx_nav_sbas_usb),
    KEY_ENTRY(msgout_ubx_nav_sig_i2c),
    KEY_ENTRY(msgout_ubx_nav_sig_spi),
    KEY_ENTRY(msgout_ubx_nav_sig_uart1),
    KEY_ENTRY(msgout_ubx_nav_sig_uart2),
    KEY_ENTRY(msgout_ubx_nav_sig_usb),
    KEY_ENTRY(msgout_ubx_nav_slas_i2c),
    KEY_ENTRY(msgout_ubx_nav_slas_spi),
    KEY_ENTRY(msgout_ubx_nav_slas_uart1),
    KEY_ENTRY(msgout_ubx_nav_slas_uart2),
    KEY_ENTRY(msgout_ubx_nav_slas_usb),
    KEY_ENTRY(msgout_ubx_nav_status_i2c),
    KEY_ENTRY(msgout_ubx_nav_status_spi),
    KEY_ENTRY(msgout_ubx_nav_status_uart1),
    KEY_ENTRY(msgout_ubx_nav_status_uart2),
    KEY_ENTRY(msgout_ubx_nav_status_usb),
    KEY_ENTRY(msgout_ubx_nav_svin_i2c),
    KEY_ENTRY(msgout_ubx_nav_svin_spi),
    KEY_ENTRY(msgout_ubx_nav_svin_uart1),
    KEY_ENTRY(msgout_ubx_nav_svin_uart2),
    KEY_ENTRY(msgout_ubx_nav_svin_usb),
    KEY_ENTRY(msgout_ubx_nav_timebds_i2c),
    KEY_ENTRY(msgout_ubx_nav_timebds_spi),
    KEY_ENTRY(msgout_ubx_nav_timebds_uart1),
    KEY_ENTRY(msgout_ubx_nav_timebds_uart2),
    KEY_ENTRY(msgout_ubx_nav_timebds_usb),
    KEY_ENTRY(msgout_ubx_nav_timegal_i2c),
    KEY_ENTRY(msgout_ubx_nav_timegal_spi),
    KEY_ENTRY(msgout_ubx_nav_timegal_uart1),
    KEY_ENTRY(msgout_ubx_nav_timegal_uart2),
    KEY_ENTRY(msgout_ubx_nav_timegal_usb),
    KEY_ENTRY(msgout_ubx_nav_timeglo_i2c),
    KEY_ENTRY(msgout_ubx_nav_timeglo_spi),
    KEY_ENTRY(msgout_ubx_nav_timeglo_uart1),
    KEY_ENTRY(msgout_ubx_nav_timeglo_uart2),
    KEY_ENTRY(msgout_ubx_nav_timeglo_usb),
    KEY_ENTRY(msgout_ubx_nav_timegps_i2c),
    KEY_ENTRY(msgout_ubx_nav_timegps_spi),
    KEY_ENTRY(msgout_ubx_nav_timegps_uart1),
    KEY_ENTRY(msgout_ubx_nav_timegps_uart2),
    KEY_ENTRY(msgout_ubx_nav_timegps_usb),
    KEY_ENTRY(msgout_ubx_nav_timels_i2c),
    KEY_ENTRY(msgout_ubx_nav_timels_spi),
    KEY_ENTRY(msgout_ubx_nav_timels_uart1),
    KEY_ENTRY(msgout_ubx_nav_timels_uart2),
    KEY_ENTRY(msgout_ubx_nav_timels_usb),
    KEY_ENTRY(msgout_ubx_nav_timeqzss_i2c),
    KEY_ENTRY(msgout_ubx_nav_timeqzss_spi),
    KEY_ENTRY(msgout_ubx_nav_timeqzss_uart1),
    KEY_ENTRY(msgout_ubx_nav_timeqzss_uart2),
    KEY_ENTRY(msgout_ubx_nav_timeqzss_usb),
    KEY_ENTRY(msgout_ubx_nav_timeutc_i2c),
    KEY_ENTRY(msgout_ubx_nav_timeutc_spi),
    KEY_ENTRY(msgout_ubx_nav_timeutc_uart1),
    KEY_ENTRY(msgout_ubx_nav_timeutc_uart2),
    KEY_ENTRY(msgout_ubx_nav_timeutc_usb),
    KEY_ENTRY(msgout_ubx_nav_velecef_i2c),
    KEY_ENTRY(msgout_ubx_nav_velecef_spi),
    KEY_ENTRY(msgout_ubx_nav_velecef_uart1),
    KEY_ENTRY(msgout_ubx_nav_velecef_uart2),
    KEY_ENTRY(msgout_ubx_nav_velecef_usb),
    KEY_ENTRY(msgout_ubx_nav_velned_i2c),
    KEY_ENTRY(msgout_ubx_nav_velned_spi),
    KEY_ENTRY(msgout_ubx_nav_velned_uart1),
    KEY_ENTRY(msgout_ubx_nav_velned_uart2),
    KEY_ENTRY(msgout_ubx_nav_velned_usb),

    // MSGOUT — UBX RXM
    KEY_ENTRY(msgout_ubx_rxm_cor_i2c),
    KEY_ENTRY(msgout_ubx_rxm_cor_spi),
    KEY_ENTRY(msgout_ubx_rxm_cor_uart1),
    KEY_ENTRY(msgout_ubx_rxm_cor_uart2),
    KEY_ENTRY(msgout_ubx_rxm_cor_usb),
    KEY_ENTRY(msgout_ubx_rxm_measx_i2c),
    KEY_ENTRY(msgout_ubx_rxm_measx_spi),
    KEY_ENTRY(msgout_ubx_rxm_measx_uart1),
    KEY_ENTRY(msgout_ubx_rxm_measx_uart2),
    KEY_ENTRY(msgout_ubx_rxm_measx_usb),
    KEY_ENTRY(msgout_ubx_rxm_pmp_i2c),
    KEY_ENTRY(msgout_ubx_rxm_pmp_spi),
    KEY_ENTRY(msgout_ubx_rxm_pmp_uart1),
    KEY_ENTRY(msgout_ubx_rxm_pmp_uart2),
    KEY_ENTRY(msgout_ubx_rxm_pmp_usb),
    KEY_ENTRY(msgout_ubx_rxm_qzssl6_uart1),
    KEY_ENTRY(msgout_ubx_rxm_qzssl6_uart2),
    KEY_ENTRY(msgout_ubx_rxm_qzssl6_usb),
    KEY_ENTRY(msgout_ubx_rxm_qzssl6_i2c),
    KEY_ENTRY(msgout_ubx_rxm_qzssl6_spi),
    KEY_ENTRY(msgout_ubx_rxm_rawx_i2c),
    KEY_ENTRY(msgout_ubx_rxm_rawx_spi),
    KEY_ENTRY(msgout_ubx_rxm_rawx_uart1),
    KEY_ENTRY(msgout_ubx_rxm_rawx_uart2),
    KEY_ENTRY(msgout_ubx_rxm_rawx_usb),
    KEY_ENTRY(msgout_ubx_rxm_rlm_i2c),
    KEY_ENTRY(msgout_ubx_rxm_rlm_spi),
    KEY_ENTRY(msgout_ubx_rxm_rlm_uart1),
    KEY_ENTRY(msgout_ubx_rxm_rlm_uart2),
    KEY_ENTRY(msgout_ubx_rxm_rlm_usb),
    KEY_ENTRY(msgout_ubx_rxm_rtc5_i2c),
    KEY_ENTRY(msgout_ubx_rxm_rtc5_spi),
    KEY_ENTRY(msgout_ubx_rxm_rtc5_uart1),
    KEY_ENTRY(msgout_ubx_rxm_rtc5_uart2),
    KEY_ENTRY(msgout_ubx_rxm_rtc5_usb),
    KEY_ENTRY(msgout_ubx_rxm_rtcm_i2c),
    KEY_ENTRY(msgout_ubx_rxm_rtcm_spi),
    KEY_ENTRY(msgout_ubx_rxm_rtcm_uart1),
    KEY_ENTRY(msgout_ubx_rxm_rtcm_uart2),
    KEY_ENTRY(msgout_ubx_rxm_rtcm_usb),
    KEY_ENTRY(msgout_ubx_rxm_sfrbx_i2c),
    KEY_ENTRY(msgout_ubx_rxm_sfrbx_spi),
    KEY_ENTRY(msgout_ubx_rxm_sfrbx_uart1),
    KEY_ENTRY(msgout_ubx_rxm_sfrbx_uart2),
    KEY_ENTRY(msgout_ubx_rxm_sfrbx_usb),
    KEY_ENTRY(msgout_ubx_rxm_spartn_i2c),
    KEY_ENTRY(msgout_ubx_rxm_spartn_spi),
    KEY_ENTRY(msgout_ubx_rxm_spartn_uart1),
    KEY_ENTRY(msgout_ubx_rxm_spartn_uart2),
    KEY_ENTRY(msgout_ubx_rxm_spartn_usb),
    KEY_ENTRY(msgout_ubx_rxm_tm_i2c),
    KEY_ENTRY(msgout_ubx_rxm_tm_spi),
    KEY_ENTRY(msgout_ubx_rxm_tm_uart1),
    KEY_ENTRY(msgout_ubx_rxm_tm_uart2),
    KEY_ENTRY(msgout_ubx_rxm_tm_usb),

    // MSGOUT — UBX SEC
    KEY_ENTRY(msgout_ubx_sec_crc_i2c),
    KEY_ENTRY(msgout_ubx_sec_crc_spi),
    KEY_ENTRY(msgout_ubx_sec_crc_uart1),
    KEY_ENTRY(msgout_ubx_sec_crc_uart2),
    KEY_ENTRY(msgout_ubx_sec_crc_usb),
    KEY_ENTRY(msgout_ubx_sec_sig_i2c),
    KEY_ENTRY(msgout_ubx_sec_sig_spi),
    KEY_ENTRY(msgout_ubx_sec_sig_uart1),
    KEY_ENTRY(msgout_ubx_sec_sig_uart2),
    KEY_ENTRY(msgout_ubx_sec_sig_usb),
    KEY_ENTRY(msgout_ubx_sec_siglog_i2c),
    KEY_ENTRY(msgout_ubx_sec_siglog_spi),
    KEY_ENTRY(msgout_ubx_sec_siglog_uart1),
    KEY_ENTRY(msgout_ubx_sec_siglog_uart2),
    KEY_ENTRY(msgout_ubx_sec_siglog_usb),

    // MSGOUT — UBX TIM
    KEY_ENTRY(msgout_ubx_tim_tm2_i2c),
    KEY_ENTRY(msgout_ubx_tim_tm2_spi),
    KEY_ENTRY(msgout_ubx_tim_tm2_uart1),
    KEY_ENTRY(msgout_ubx_tim_tm2_uart2),
    KEY_ENTRY(msgout_ubx_tim_tm2_usb),
    KEY_ENTRY(msgout_ubx_tim_tp_i2c),
    KEY_ENTRY(msgout_ubx_tim_tp_spi),
    KEY_ENTRY(msgout_ubx_tim_tp_uart1),
    KEY_ENTRY(msgout_ubx_tim_tp_uart2),
    KEY_ENTRY(msgout_ubx_tim_tp_usb),
    KEY_ENTRY(msgout_ubx_tim_vrfy_i2c),
    KEY_ENTRY(msgout_ubx_tim_vrfy_spi),
    KEY_ENTRY(msgout_ubx_tim_vrfy_uart1),
    KEY_ENTRY(msgout_ubx_tim_vrfy_uart2),
    KEY_ENTRY(msgout_ubx_tim_vrfy_usb),

    // NAV2
    KEY_ENTRY(nav2_out_enabled),
    KEY_ENTRY(nav2_sbas_use_integrity),

    // NAVHPG
    KEY_ENTRY(navhpg_dgnssmode),

    // NAVSPG
    KEY_ENTRY(navspg_fixmode),
    KEY_ENTRY(navspg_inifix3d),
    KEY_ENTRY(navspg_wknrollover),
    KEY_ENTRY(navspg_use_ppp),
    KEY_ENTRY(navspg_utcstandard),
    KEY_ENTRY(navspg_dynmodel),
    KEY_ENTRY(navspg_ackaiding),
    KEY_ENTRY(navspg_usrdat),
    KEY_ENTRY(navspg_usrdat_maja),
    KEY_ENTRY(navspg_usrdat_flat),
    KEY_ENTRY(navspg_usrdat_dx),
    KEY_ENTRY(navspg_usrdat_dy),
    KEY_ENTRY(navspg_usrdat_dz),
    KEY_ENTRY(navspg_usrdat_rotx),
    KEY_ENTRY(navspg_usrdat_roty),
    KEY_ENTRY(navspg_usrdat_rotz),
    KEY_ENTRY(navspg_usrdat_scale),
    KEY_ENTRY(navspg_infil_minsvs),
    KEY_ENTRY(navspg_infil_maxsvs),
    KEY_ENTRY(navspg_infil_mincno),
    KEY_ENTRY(navspg_infil_minelev),
    KEY_ENTRY(navspg_infil_ncnothrs),
    KEY_ENTRY(navspg_infil_cnothrs),
    KEY_ENTRY(navspg_outfil_pdop),
    KEY_ENTRY(navspg_outfil_tdop),
    KEY_ENTRY(navspg_outfil_pacc),
    KEY_ENTRY(navspg_outfil_tacc),
    KEY_ENTRY(navspg_outfil_facc),
    KEY_ENTRY(navspg_constr_alt),
    KEY_ENTRY(navspg_constr_altvar),
    KEY_ENTRY(navspg_constr_dgnssto),
    KEY_ENTRY(navspg_sigattcomp),
    KEY_ENTRY(navspg_pl_ena),

    // NMEA
    KEY_ENTRY(nmea_protver),
    KEY_ENTRY(nmea_maxsvs),
    KEY_ENTRY(nmea_compat),
    KEY_ENTRY(nmea_consider),
    KEY_ENTRY(nmea_limit82),
    KEY_ENTRY(nmea_highprec),
    KEY_ENTRY(nmea_svnumbering),
    KEY_ENTRY(nmea_filt_gps),
    KEY_ENTRY(nmea_filt_sbas),
    KEY_ENTRY(nmea_filt_gal),
    KEY_ENTRY(nmea_filt_qzss),
    KEY_ENTRY(nmea_filt_glo),
    KEY_ENTRY(nmea_filt_bds),
    KEY_ENTRY(nmea_out_invfix),
    KEY_ENTRY(nmea_out_mskfix),
    KEY_ENTRY(nmea_out_invtime),
    KEY_ENTRY(nmea_out_invdate),
    KEY_ENTRY(nmea_out_onlygps),
    KEY_ENTRY(nmea_out_frozencog),
    KEY_ENTRY(nmea_maintalkerid),
    KEY_ENTRY(nmea_gsvtalkerid),
    KEY_ENTRY(nmea_bdstalkerid),

    // ODO
    KEY_ENTRY(odo_use_odo),
    KEY_ENTRY(odo_use_cog),
    KEY_ENTRY(odo_outlpvel),
    KEY_ENTRY(odo_outlpcog),
    KEY_ENTRY(odo_profile),
    KEY_ENTRY(odo_cogmaxspeed),
    KEY_ENTRY(odo_cogmaxposacc),
    KEY_ENTRY(odo_vellpgain),
    KEY_ENTRY(odo_coglpgain),

    // PM
    KEY_ENTRY(pm_operatemode),
    KEY_ENTRY(pm_posupdateperiod),
    KEY_ENTRY(pm_acqperiod),
    KEY_ENTRY(pm_gridoffset),
    KEY_ENTRY(pm_ontime),
    KEY_ENTRY(pm_minfixacc),
    KEY_ENTRY(pm_donotenterhot),
    KEY_ENTRY(pm_waittimefix),
    KEY_ENTRY(pm_updateeph),
    KEY_ENTRY(pm_extintsel),
    KEY_ENTRY(pm_extintwake),
    KEY_ENTRY(pm_extintbackup),
    KEY_ENTRY(pm_extintinactive),
    KEY_ENTRY(pm_extintinactivity),
    KEY_ENTRY(pm_limitpeakcurr),

    // PMP
    KEY_ENTRY(pmp_center_frequency),
    KEY_ENTRY(pmp_search_window),
    KEY_ENTRY(pmp_use_service_id),
    KEY_ENTRY(pmp_service_id),
    KEY_ENTRY(pmp_data_rate),
    KEY_ENTRY(pmp_use_descrambler),
    KEY_ENTRY(pmp_descrambler_init),
    KEY_ENTRY(pmp_use_prescrambling),
    KEY_ENTRY(pmp_unique_word),

    // QZSS
    KEY_ENTRY(qzss_use_slas_dgnss),
    KEY_ENTRY(qzss_use_slas_testmode),
    KEY_ENTRY(qzss_use_slas_raim_uncorr),
    KEY_ENTRY(qzss_slas_max_baseline),
    KEY_ENTRY(qzss_l6_svida),
    KEY_ENTRY(qzss_l6_svidb),
    KEY_ENTRY(qzss_l6_msga),
    KEY_ENTRY(qzss_l6_msgb),
    KEY_ENTRY(qzss_l6_rsdecoder),

    // RATE
    KEY_ENTRY(rate_meas),
    KEY_ENTRY(rate_nav),
    KEY_ENTRY(rate_timeref),
    KEY_ENTRY(rate_nav_prio),

    // RINV
    KEY_ENTRY(rinv_dump),
    KEY_ENTRY(rinv_binary),
    KEY_ENTRY(rinv_data_size),
    KEY_ENTRY(rinv_chunk0),
    KEY_ENTRY(rinv_chunk1),
    KEY_ENTRY(rinv_chunk2),
    KEY_ENTRY(rinv_chunk3),

    // RTCM
    KEY_ENTRY(rtcm_df003_out),
    KEY_ENTRY(rtcm_df003_in),
    KEY_ENTRY(rtcm_df003_in_filter),

    // SBAS
    KEY_ENTRY(sbas_use_testmode),
    KEY_ENTRY(sbas_use_ranging),
    KEY_ENTRY(sbas_use_diffcorr),
    KEY_ENTRY(sbas_use_integrity),
    KEY_ENTRY(sbas_prnscanmask),

    // SEC
    KEY_ENTRY(sec_cfg_lock),
    KEY_ENTRY(sec_cfg_lock_unlockgrp1),
    KEY_ENTRY(sec_cfg_lock_unlockgrp2),
    KEY_ENTRY(sec_jamdet_sensitivity_hi),

    // SFCORE
    KEY_ENTRY(sfcore_use_sf),
    KEY_ENTRY(sfcore_imu2crp_la_x),
    KEY_ENTRY(sfcore_imu2crp_la_y),
    KEY_ENTRY(sfcore_imu2crp_la_z),
    KEY_ENTRY(sfcore_sen_ttag_fact),
    KEY_ENTRY(sfcore_sen_ttag_max),
    KEY_ENTRY(sfcore_outfil_pacc),

    // SFIMU
    KEY_ENTRY(sfimu_gyro_tc_update_period),
    KEY_ENTRY(sfimu_gyro_rmsthdl),
    KEY_ENTRY(sfimu_gyro_frequency),
    KEY_ENTRY(sfimu_gyro_latency),
    KEY_ENTRY(sfimu_gyro_accuracy),
    KEY_ENTRY(sfimu_accel_rmsthdl),
    KEY_ENTRY(sfimu_accel_frequency),
    KEY_ENTRY(sfimu_accel_latency),
    KEY_ENTRY(sfimu_accel_accuracy),
    KEY_ENTRY(sfimu_imu_en),
    KEY_ENTRY(sfimu_imu_i2c_scl_pio),
    KEY_ENTRY(sfimu_imu_i2c_sda_pio),
    KEY_ENTRY(sfimu_imu2ant_la_x),
    KEY_ENTRY(sfimu_imu2ant_la_y),
    KEY_ENTRY(sfimu_imu2ant_la_z),
    KEY_ENTRY(sfimu_auto_mntalg_ena),
    KEY_ENTRY(sfimu_imu_mntalg_yaw),
    KEY_ENTRY(sfimu_imu_mntalg_pitch),
    KEY_ENTRY(sfimu_imu_mntalg_roll),

    // SFODO
    KEY_ENTRY(sfodo_combine_ticks),
    KEY_ENTRY(sfodo_use_speed),
    KEY_ENTRY(sfodo_dis_autocountmax),
    KEY_ENTRY(sfodo_dis_autodirpinpol),
    KEY_ENTRY(sfodo_dis_autospeed),
    KEY_ENTRY(sfodo_factor),
    KEY_ENTRY(sfodo_quant_error),
    KEY_ENTRY(sfodo_count_max),
    KEY_ENTRY(sfodo_latency),
    KEY_ENTRY(sfodo_frequency),
    KEY_ENTRY(sfodo_cnt_both_edges),
    KEY_ENTRY(sfodo_speed_band),
    KEY_ENTRY(sfodo_use_wt_pin),
    KEY_ENTRY(sfodo_dir_pinpol),
    KEY_ENTRY(sfodo_dis_autosw),
    KEY_ENTRY(sfodo_imu2vrp_la_x),
    KEY_ENTRY(sfodo_imu2vrp_la_y),
    KEY_ENTRY(sfodo_imu2vrp_la_z),
    KEY_ENTRY(sfodo_trackgauge_rear),
    KEY_ENTRY(sfodo_dis_dir_info),

    // SIGNAL
    KEY_ENTRY(signal_gps_ena),
    KEY_ENTRY(signal_gps_l1ca_ena),
    KEY_ENTRY(signal_gps_l2c_ena),
    KEY_ENTRY(signal_gps_l5_ena),
    KEY_ENTRY(signal_sbas_ena),
    KEY_ENTRY(signal_sbas_l1ca_ena),
    KEY_ENTRY(signal_gal_ena),
    KEY_ENTRY(signal_gal_e1_ena),
    KEY_ENTRY(signal_gal_e5a_ena),
    KEY_ENTRY(signal_gal_e5b_ena),
    KEY_ENTRY(signal_bds_ena),
    KEY_ENTRY(signal_bds_b1_ena),
    KEY_ENTRY(signal_bds_b2_ena),
    KEY_ENTRY(signal_bds_b1c_ena),
    KEY_ENTRY(signal_bds_b2a_ena),
    KEY_ENTRY(signal_qzss_ena),
    KEY_ENTRY(signal_qzss_l1ca_ena),
    KEY_ENTRY(signal_qzss_l1s_ena),
    KEY_ENTRY(signal_qzss_l2c_ena),
    KEY_ENTRY(signal_qzss_l5_ena),
    KEY_ENTRY(signal_glo_ena),
    KEY_ENTRY(signal_glo_l1_ena),
    KEY_ENTRY(signal_glo_l2_ena),
    KEY_ENTRY(signal_navic_ena),
    KEY_ENTRY(signal_navic_l5_ena),

    // SPARTN
    KEY_ENTRY(spartn_use_source),

    // SPI
    KEY_ENTRY(spi_maxff),
    KEY_ENTRY(spi_cpolarity),
    KEY_ENTRY(spi_cphase),
    KEY_ENTRY(spi_extendedtimeout),
    KEY_ENTRY(spi_enabled),

    // SPIINPROT
    KEY_ENTRY(spiinprot_ubx),
    KEY_ENTRY(spiinprot_nmea),
    KEY_ENTRY(spiinprot_rtcm3x),
    KEY_ENTRY(spiinprot_spartn),

    // SPIOUTPROT
    KEY_ENTRY(spioutprot_ubx),
    KEY_ENTRY(spioutprot_nmea),
    KEY_ENTRY(spioutprot_rtcm3x),

    // TMODE
    KEY_ENTRY(tmode_mode),
    KEY_ENTRY(tmode_pos_type),
    KEY_ENTRY(tmode_ecef_x),
    KEY_ENTRY(tmode_ecef_y),
    KEY_ENTRY(tmode_ecef_z),
    KEY_ENTRY(tmode_ecef_x_hp),
    KEY_ENTRY(tmode_ecef_y_hp),
    KEY_ENTRY(tmode_ecef_z_hp),
    KEY_ENTRY(tmode_lat),
    KEY_ENTRY(tmode_lon),
    KEY_ENTRY(tmode_height),
    KEY_ENTRY(tmode_lat_hp),
    KEY_ENTRY(tmode_lon_hp),
    KEY_ENTRY(tmode_height_hp),
    KEY_ENTRY(tmode_fixed_pos_acc),
    KEY_ENTRY(tmode_svin_min_dur),
    KEY_ENTRY(tmode_svin_acc_limit),

    // TP
    KEY_ENTRY(tp_pulse_def),
    KEY_ENTRY(tp_pulse_length_def),
    KEY_ENTRY(tp_ant_cabledelay),
    KEY_ENTRY(tp_period_tp1),
    KEY_ENTRY(tp_period_lock_tp1),
    KEY_ENTRY(tp_freq_tp1),
    KEY_ENTRY(tp_freq_lock_tp1),
    KEY_ENTRY(tp_len_tp1),
    KEY_ENTRY(tp_len_lock_tp1),
    KEY_ENTRY(tp_duty_tp1),
    KEY_ENTRY(tp_duty_lock_tp1),
    KEY_ENTRY(tp_user_delay_tp1),
    KEY_ENTRY(tp_tp1_ena),
    KEY_ENTRY(tp_sync_gnss_tp1),
    KEY_ENTRY(tp_use_locked_tp1),
    KEY_ENTRY(tp_align_to_tow_tp1),
    KEY_ENTRY(tp_pol_tp1),
    KEY_ENTRY(tp_timegrid_tp1),
    KEY_ENTRY(tp_drstr_tp1),
    KEY_ENTRY(tp_period_tp2),
    KEY_ENTRY(tp_period_lock_tp2),
    KEY_ENTRY(tp_freq_tp2),
    KEY_ENTRY(tp_freq_lock_tp2),
    KEY_ENTRY(tp_len_tp2),
    KEY_ENTRY(tp_len_lock_tp2),
    KEY_ENTRY(tp_duty_tp2),
    KEY_ENTRY(tp_duty_lock_tp2),
    KEY_ENTRY(tp_user_delay_tp2),
    KEY_ENTRY(tp_tp2_ena),
    KEY_ENTRY(tp_sync_gnss_tp2),
    KEY_ENTRY(tp_use_locked_tp2),
    KEY_ENTRY(tp_align_to_tow_tp2),
    KEY_ENTRY(tp_pol_tp2),
    KEY_ENTRY(tp_timegrid_tp2),
    KEY_ENTRY(tp_drstr_tp2),

    // TXREADY
    KEY_ENTRY(txready_enabled),
    KEY_ENTRY(txready_polarity),
    KEY_ENTRY(txready_pin),
    KEY_ENTRY(txready_threshold),
    KEY_ENTRY(txready_interface),

    // UART1
    KEY_ENTRY(uart1_baudrate),
    KEY_ENTRY(uart1_stopbits),
    KEY_ENTRY(uart1_databits),
    KEY_ENTRY(uart1_parity),
    KEY_ENTRY(uart1_enabled),

    // UART1INPROT
    KEY_ENTRY(uart1inprot_ubx),
    KEY_ENTRY(uart1inprot_nmea),
    KEY_ENTRY(uart1inprot_rtcm3x),
    KEY_ENTRY(uart1inprot_spartn),

    // UART1OUTPROT
    KEY_ENTRY(uart1outprot_ubx),
    KEY_ENTRY(uart1outprot_nmea),
    KEY_ENTRY(uart1outprot_rtcm3x),

    // UART2
    KEY_ENTRY(uart2_baudrate),
    KEY_ENTRY(uart2_stopbits),
    KEY_ENTRY(uart2_databits),
    KEY_ENTRY(uart2_parity),
    KEY_ENTRY(uart2_enabled),

    // UART2INPROT
    KEY_ENTRY(uart2inprot_ubx),
    KEY_ENTRY(uart2inprot_nmea),
    KEY_ENTRY(uart2inprot_rtcm3x),
    KEY_ENTRY(uart2inprot_spartn),

    // UART2OUTPROT
    KEY_ENTRY(uart2outprot_ubx),
    KEY_ENTRY(uart2outprot_nmea),
    KEY_ENTRY(uart2outprot_rtcm3x),

    // USB
    KEY_ENTRY(usb_enabled),
    KEY_ENTRY(usb_selfpow),
    KEY_ENTRY(usb_vendor_id),
    KEY_ENTRY(usb_product_id),
    KEY_ENTRY(usb_power),
    KEY_ENTRY(usb_vendor_str0),
    KEY_ENTRY(usb_vendor_str1),
    KEY_ENTRY(usb_vendor_str2),
    KEY_ENTRY(usb_vendor_str3),
    KEY_ENTRY(usb_product_str0),
    KEY_ENTRY(usb_product_str1),
    KEY_ENTRY(usb_product_str2),
    KEY_ENTRY(usb_product_str3),
    KEY_ENTRY(usb_serial_no_str0),
    KEY_ENTRY(usb_serial_no_str1),
    KEY_ENTRY(usb_serial_no_str2),
    KEY_ENTRY(usb_serial_no_str3),

    // USBINPROT
    KEY_ENTRY(usbinprot_ubx),
    KEY_ENTRY(usbinprot_nmea),
    KEY_ENTRY(usbinprot_rtcm3x),
    KEY_ENTRY(usbinprot_spartn),

    // USBOUTPROT
    KEY_ENTRY(usboutprot_ubx),
    KEY_ENTRY(usboutprot_nmea),
    KEY_ENTRY(usboutprot_rtcm3x),
};

#undef KEY_ENTRY

static const std::size_t s_key_table_size =
    sizeof(s_key_table) / sizeof(s_key_table[0]);

// ─── Public API ───────────────────────────────────────────────────────────────

bool ubx_cfg_key_registry::lookup_by_name(const char* name, uint32_t& out_key_id)
{
    if (!name) return false;
    for (std::size_t i = 0u; i < s_key_table_size; ++i)
    {
        if (std::strcmp(s_key_table[i].name, name) == 0)
        {
            out_key_id = s_key_table[i].key_id;
            return true;
        }
    }
    return false;
}

const char* ubx_cfg_key_registry::lookup_by_id(uint32_t key_id)
{
    for (std::size_t i = 0u; i < s_key_table_size; ++i)
    {
        if (s_key_table[i].key_id == key_id)
        {
            return s_key_table[i].name;
        }
    }
    return nullptr;
}

const key_info* ubx_cfg_key_registry::table()
{
    return s_key_table;
}

std::size_t ubx_cfg_key_registry::table_size()
{
    return s_key_table_size;
}

} // namespace config
} // namespace ubx
